# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title_html: "<b>yuri</b>gladkov"
description: > # this means to ignore newlines until "baseurl:"
pitch: CV and personal blog
nb_posts_page: 5
email: cyberglad@gmail.com
shortbio: I am a Senior Java Developer @Swisscom
twitter_username: cyberglad
github_username: cyberglad
linkedin_username: yurigladkov
langs: ["fr", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "fr"
title:
  fr: "Site personelle de Yuri Gladkov"
  en: "Personal site of Yuri Gladkov"      
